version: '3.5'
services:
    elasticsearch:
        container_name: elasticsearch
        build: elasticsearch
        volumes:
            - esdata:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        expose:
            - 9300
        environment:
            - discovery.type=single-node
        networks:
            - elasticsearch_network
        # restart: always
    kibana:
        container_name: kibana
        build: kibana
        ports:
            - 5601:5601
        environment:
            - I18N_LOCALE="ja-JP"
        networks:
            - elasticsearch_network
        # restart: always
    # selenium:
    #     container_name: selenium
    #     build: selenium
    #     ports:
    #         - 4444:4444
    #     volumes:
    #         - /dev/shm:/dev/shm
    #     environment:
    #         - SE_OPTS=-sessionTimeout 86400
    #     networks:
    #         - elasticsearch_network
    collector:
        container_name: collector
        build: collector
        volumes:
            - chatdata:/var/lib/app/superchat/
            - "./log/debug/:/var/lib/app/debug/"
            - "./secret/credentials.json:/var/lib/app/credentials.json"
            - "./secret/token.json:/var/lib/app/token.json"
        environment:
            - YOUTUBE_WATCH_LIVE_KEY1
            - YOUTUBE_WATCH_LIVE_KEY2
            - YOUTUBE_WATCH_LIVE_KEY3
            - YOUTUBE_WATCH_LIVE_KEY4
            - YOUTUBE_WATCH_LIVE_KEY5
            - YOUTUBE_WATCH_LIVE_KEY6
            - YOUTUBE_WATCH_LIVE_KEY7
            - YOUTUBE_WATCH_LIVE_KEY8
            - YOUTUBE_WATCH_LIVE_KEY9
            - SUPER_CHAT_SENTRY_DSN
            - GIT_COMMIT
        networks:
            - elasticsearch_network
        # restart: always
    archive_collector:
        container_name: archive_collector
        build: archive_collector
        tty: true
        volumes:
            - arvhivedata:/var/lib/app/superchat/
            - "./log/debug2/:/var/lib/app/debug/"
        environment:
            - YOUTUBE_WATCH_LIVE_KEY_ARCHIVE
        networks:
            - elasticsearch_network
        # restart: always
    data:
        container_name: data
        image: ubuntu:18.04
        tty: true
        volumes:
            - chatdata:/var/lib/app/superchat/
            - arvhivedata:/var/lib/app/archive/
        networks:
            - elasticsearch_network
        # restart: always
volumes:
    esdata:
        driver: local
    chatdata:
        driver: local
    arvhivedata:
        driver: local

networks:
    elasticsearch_network:
        name: "esnetwork"
