version: '2'
services:
  elasticsearch:
    build: elasticsearch
    volumes:
        - esdata:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    expose:
        - 9300
    environment:
        - discovery.type=single-node
  kibana:
    build: kibana
    ports:
        - 5601:5601
    environment:
        - I18N_LOCALE="ja-JP"
#    volumes:
#        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  selenium:
    build: selenium
    ports:
        - 4444:4444
    volumes:
        - /dev/shm:/dev/shm
  collector:
    build: collector
    volumes:
      - ./log/debug/:/go/bin/debug/
      - ./log/superchat/:/go/bin/superchat/
      - ./secret/credentials.json:/go/bin/credentials.json
volumes:
  esdata:
    driver: local
