version: '2'
services:
  elasticsearch:
    build: elasticsearch
    volumes:
        - esdata:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    expose:
        - 9300
    environment:
        - discovery.type=single-node
  kibana:
    build: kibana
    ports:
        - 5601:5601
    environment:
        - I18N_LOCALE="ja-JP"
#    volumes:
#        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
volumes:
  esdata:
    driver: local

