version: '2'
services:
  elasticsearch:
    build: elasticsearch
    volumes:
        - esdata:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    expose:
        - 9300
    environment:
        - discovery.type=single-node
  kibana:
    build: kibana
    ports:
        - 5601:5601
    environment:
        - I18N_LOCALE="ja-JP"
#    volumes:
#        - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
  selenium:
    build: selenium
    ports:
        - 4444:4444
    volumes:
        - /dev/shm:/dev/shm
  collector:
    build: collector
    volumes:
      - ./log/debug/:/var/lib/app/debug/
      - ./log/superchat/:/var/lib/app/superchat/
      - ./secret/credentials.json:/var/lib/app/credentials.json
    environment:
      - YOUTUBE_WATCH_LIVE_KEY1
      - YOUTUBE_WATCH_LIVE_KEY2
      - YOUTUBE_WATCH_LIVE_KEY3
      - YOUTUBE_WATCH_LIVE_KEY4
      - YOUTUBE_WATCH_LIVE_KEY5
      - YOUTUBE_WATCH_LIVE_KEY6
      - YOUTUBE_WATCH_LIVE_KEY7
      - YOUTUBE_WATCH_LIVE_KEY8
      - YOUTUBE_WATCH_LIVE_KEY9
volumes:
  esdata:
    driver: local
